<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 부록 (APPENDIX) | 데이터 과학 라이브 북 (Data Science Live Book)</title>
  <meta name="description" content="나이에 상관없이 누구나 배울 수 있는 데이터 분석, 데이터 준비 및 머신러닝에 대한 직관적이고 실용적인 접근법!" />
  <meta name="generator" content="bookdown 0.46.2 and GitBook 2.6.7" />

  <meta property="og:title" content="5 부록 (APPENDIX) | 데이터 과학 라이브 북 (Data Science Live Book)" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://livebook.datascienceheroes.com/introduction/data_science_live_book_cover.png" />
  <meta property="og:description" content="나이에 상관없이 누구나 배울 수 있는 데이터 분석, 데이터 준비 및 머신러닝에 대한 직관적이고 실용적인 접근법!" />
  <meta name="github-repo" content="pablo14/data-science-live-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 부록 (APPENDIX) | 데이터 과학 라이브 북 (Data Science Live Book)" />
  <meta name="twitter:site" content="@pabloc_ds" />
  <meta name="twitter:description" content="나이에 상관없이 누구나 배울 수 있는 데이터 분석, 데이터 준비 및 머신러닝에 대한 직관적이고 실용적인 접근법!" />
  <meta name="twitter:image" content="https://livebook.datascienceheroes.com/introduction/data_science_live_book_cover.png" />

<meta name="author" content="Pablo Casas (번역: fkt)" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="introduction/favicon.ico" type="image/x-icon" />
<link rel="prev" href="model-performance.html"/>
<link rel="next" href="download-book.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82047152-1', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science Live Book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>서문 (Preface)</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#종이책-킨들-amazon"><i class="fa fa-check"></i>종이책 &amp; 킨들 (Amazon)</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#왜-이-책인가요"><i class="fa fa-check"></i>왜 이 책인가요?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#배움을-향한-여정"><i class="fa fa-check"></i>배움을 향한 여정</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#이-책이-나에게-맞을까요-이해할-수-있을까요"><i class="fa fa-check"></i>이 책이 나에게 맞을까요? 이해할 수 있을까요?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#프로그래밍-언어"><i class="fa fa-check"></i>프로그래밍 언어</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#기계와-인공지능이-세상을-지배하게-될까요"><i class="fa fa-check"></i>기계와 인공지능이 세상을 지배하게 될까요? 😱</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#시작하려면-무엇이-필요한가요"><i class="fa fa-check"></i>시작하려면 무엇이 필요한가요?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#연락은-어떻게-하나요"><i class="fa fa-check"></i>연락은 어떻게 하나요? 📩</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#감사의-말"><i class="fa fa-check"></i>감사의 말</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#책-정보"><i class="fa fa-check"></i>책 정보</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html"><i class="fa fa-check"></i><b>1</b> 탐색적 데이터 분석</a>
<ul>
<li class="chapter" data-level="1.1" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#profiling"><i class="fa fa-check"></i><b>1.1</b> 프로파일링: 숫자의 목소리</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#데이터셋-상태-dataset-health-status"><i class="fa fa-check"></i><b>1.1.1</b> 데이터셋 상태 {#dataset-health-status}</a></li>
<li class="chapter" data-level="1.1.2" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#범주형-변수-프로파일링-profiling-categorical-variables"><i class="fa fa-check"></i><b>1.1.2</b> 범주형 변수 프로파일링 {#profiling-categorical-variables}</a></li>
<li class="chapter" data-level="1.1.3" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#수치형-변수-프로파일링"><i class="fa fa-check"></i><b>1.1.3</b> 수치형 변수 프로파일링</a></li>
<li class="chapter" data-level="1.1.4" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#최종-생각"><i class="fa fa-check"></i><b>1.1.4</b> 최종 생각</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#상관-관계-및-관계-httpswww.google.comsearchq23correlation"><i class="fa fa-check"></i><b>1.2</b> 상관 관계 및 관계 {https://www.google.com/search?q=%23correlation}</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#이-장의-내용은-무엇일까요"><i class="fa fa-check"></i><b>1.2.1</b> 이 장의 내용은 무엇일까요?</a></li>
<li class="chapter" data-level="1.2.2" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#선형-상관-관계-linear-correlation"><i class="fa fa-check"></i><b>1.2.2</b> 선형 상관 관계 {#linear-correlation}</a></li>
<li class="chapter" data-level="1.2.3" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#정보-이론에-기반한-상관-관계"><i class="fa fa-check"></i><b>1.2.3</b> 정보 이론에 기반한 상관 관계</a></li>
<li class="chapter" data-level="1.2.4" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#노이즈-추가"><i class="fa fa-check"></i><b>1.2.4</b> 노이즈 추가</a></li>
<li class="chapter" data-level="1.2.5" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#비선형성-측정-mic-r2"><i class="fa fa-check"></i><b>1.2.5</b> 비선형성 측정 (MIC-R2)</a></li>
<li class="chapter" data-level="1.2.6" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#앤스콤-쿼텟에서-정보-측정하기"><i class="fa fa-check"></i><b>1.2.6</b> 앤스콤 쿼텟에서 정보 측정하기</a></li>
<li class="chapter" data-level="1.2.7" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#비단조성-측정-mas-측정"><i class="fa fa-check"></i><b>1.2.7</b> 비단조성 측정: MAS 측정</a></li>
<li class="chapter" data-level="1.2.8" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#시계열-간의-상관-관계"><i class="fa fa-check"></i><b>1.2.8</b> 시계열 간의 상관 관계</a></li>
<li class="chapter" data-level="1.2.9" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#범주형-변수의-상관-관계"><i class="fa fa-check"></i><b>1.2.9</b> 범주형 변수의 상관 관계</a></li>
<li class="chapter" data-level="1.2.10" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#정보-이론에-기반한-상관-관계-분석-selecting_best_vars_mic"><i class="fa fa-check"></i><b>1.2.10</b> 정보 이론에 기반한 상관 관계 분석 {#selecting_best_vars_mic}</a></li>
<li class="chapter" data-level="1.2.11" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#mine만-이런-기능을-제공하나요"><i class="fa fa-check"></i><b>1.2.11</b> MINE만 이런 기능을 제공하나요?</a></li>
<li class="chapter" data-level="1.2.12" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#정보-측정-일반적인-관점"><i class="fa fa-check"></i><b>1.2.12</b> 정보 측정: 일반적인 관점</a></li>
<li class="chapter" data-level="1.2.13" data-path="exploratory_data_analysis.html"><a href="exploratory_data_analysis.html#결론"><i class="fa fa-check"></i><b>1.2.13</b> 결론</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data_preparation.html"><a href="data_preparation.html"><i class="fa fa-check"></i><b>2</b> 데이터 준비</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data_preparation.html"><a href="data_preparation.html#data_types"><i class="fa fa-check"></i><b>2.1</b> 데이터 유형 처리</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data_preparation.html"><a href="data_preparation.html#무엇에-대한-내용인가요"><i class="fa fa-check"></i><b>2.1.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="2.1.2" data-path="data_preparation.html"><a href="data_preparation.html#데이터-유형의-세계"><i class="fa fa-check"></i><b>2.1.2</b> 데이터 유형의 세계</a></li>
<li class="chapter" data-level="2.1.3" data-path="data_preparation.html"><a href="data_preparation.html#알고리즘별-데이터-유형"><i class="fa fa-check"></i><b>2.1.3</b> 알고리즘별 데이터 유형</a></li>
<li class="chapter" data-level="2.1.4" data-path="data_preparation.html"><a href="data_preparation.html#범주형-변수를-숫자형으로-변환하기"><i class="fa fa-check"></i><b>2.1.4</b> 범주형 변수를 숫자형으로 변환하기</a></li>
<li class="chapter" data-level="2.1.5" data-path="data_preparation.html"><a href="data_preparation.html#범주형인가요-수치형인가요-생각해-봅시다."><i class="fa fa-check"></i><b>2.1.5</b> 범주형인가요, 수치형인가요? 생각해 봅시다.</a></li>
<li class="chapter" data-level="2.1.6" data-path="data_preparation.html"><a href="data_preparation.html#discretizing_numerical_variables"><i class="fa fa-check"></i><b>2.1.6</b> 수치형 변수 이산화 (Discretizing numerical variables)</a></li>
<li class="chapter" data-level="2.1.7" data-path="data_preparation.html"><a href="data_preparation.html#discretization_new_data"><i class="fa fa-check"></i><b>2.1.7</b> 새로운 데이터에서의 이산화</a></li>
<li class="chapter" data-level="2.1.8" data-path="data_preparation.html"><a href="data_preparation.html#data-discretization"><i class="fa fa-check"></i><b>2.1.8</b> 자동 데이터 프레임 이산화</a></li>
<li class="chapter" data-level="2.1.9" data-path="data_preparation.html"><a href="data_preparation.html#최종-생각-1"><i class="fa fa-check"></i><b>2.1.9</b> 최종 생각</a></li>
<li class="chapter" data-level="2.1.10" data-path="data_preparation.html"><a href="data_preparation.html#보너스-트랙"><i class="fa fa-check"></i><b>2.1.10</b> 보너스 트랙 💥</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data_preparation.html"><a href="data_preparation.html#high_cardinality_descriptive_stats"><i class="fa fa-check"></i><b>2.2</b> 기술 통계에서의 고카디널리티 변수</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data_preparation.html"><a href="data_preparation.html#무엇에-대한-내용인가요-1"><i class="fa fa-check"></i><b>2.2.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="2.2.2" data-path="data_preparation.html"><a href="data_preparation.html#기술-통계에서의-고카디널리티"><i class="fa fa-check"></i><b>2.2.2</b> 기술 통계에서의 고카디널리티</a></li>
<li class="chapter" data-level="2.2.3" data-path="data_preparation.html"><a href="data_preparation.html#최종-코멘트"><i class="fa fa-check"></i><b>2.2.3</b> 최종 코멘트</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data_preparation.html"><a href="data_preparation.html#high_cardinality_predictive_modeling"><i class="fa fa-check"></i><b>2.3</b> High Cardinality Variable in Predictive Modeling</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data_preparation.html"><a href="data_preparation.html#무엇에-대한-내용인가요-2"><i class="fa fa-check"></i><b>2.3.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="2.3.2" data-path="data_preparation.html"><a href="data_preparation.html#하지만-변수를-재그룹화하는-것이-필요할까요"><i class="fa fa-check"></i><b>2.3.2</b> 하지만 변수를 재그룹화하는 것이 필요할까요?</a></li>
<li class="chapter" data-level="2.3.3" data-path="data_preparation.html"><a href="data_preparation.html#analyze-binary-outcome-vs-categorical-variable"><i class="fa fa-check"></i><b>2.3.3</b> 사례 🔍</a></li>
<li class="chapter" data-level="2.3.4" data-path="data_preparation.html"><a href="data_preparation.html#예측-모델링을-위한-분석"><i class="fa fa-check"></i><b>2.3.4</b> 예측 모델링을 위한 분석 🔮</a></li>
<li class="chapter" data-level="2.3.5" data-path="data_preparation.html"><a href="data_preparation.html#예측-모델이-운영-환경에-있을-때-새로운-카테고리-처리하기"><i class="fa fa-check"></i><b>2.3.5</b> 예측 모델이 운영 환경에 있을 때 새로운 카테고리 처리하기</a></li>
<li class="chapter" data-level="2.3.6" data-path="data_preparation.html"><a href="data_preparation.html#예측-모델이-고카디널리티를-처리하나요-파트-1"><i class="fa fa-check"></i><b>2.3.6</b> 예측 모델이 고카디널리티를 처리하나요? 파트 1</a></li>
<li class="chapter" data-level="2.3.7" data-path="data_preparation.html"><a href="data_preparation.html#high_cardinality_in_predictive_models_part_2"><i class="fa fa-check"></i><b>2.3.7</b> 예측 모델이 고카디널리티를 처리하지 않나요? 파트 2</a></li>
<li class="chapter" data-level="2.3.8" data-path="data_preparation.html"><a href="data_preparation.html#수치형-또는-다중-공선성-타겟-변수"><i class="fa fa-check"></i><b>2.3.8</b> 수치형 또는 다중 공선성 타겟 변수 📏</a></li>
<li class="chapter" data-level="2.3.9" data-path="data_preparation.html"><a href="data_preparation.html#그룹화에서-얻은-추가-선물-은-무엇인가요"><i class="fa fa-check"></i><b>2.3.9</b> 그룹화에서 얻은 “추가 선물 🎁”은 무엇인가요?</a></li>
<li class="chapter" data-level="2.3.10" data-path="data_preparation.html"><a href="data_preparation.html#대표성-또는-샘플-크기"><i class="fa fa-check"></i><b>2.3.10</b> 대표성 또는 샘플 크기</a></li>
<li class="chapter" data-level="2.3.11" data-path="data_preparation.html"><a href="data_preparation.html#최종-생각-2"><i class="fa fa-check"></i><b>2.3.11</b> 최종 생각</a></li>
<li class="chapter" data-level="2.3.12" data-path="data_preparation.html"><a href="data_preparation.html#추가-읽기"><i class="fa fa-check"></i><b>2.3.12</b> 추가 읽기</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data_preparation.html"><a href="data_preparation.html#treatment_outliers"><i class="fa fa-check"></i><b>2.4</b> 이상치 처리 (Treatment of outliers)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data_preparation.html"><a href="data_preparation.html#무엇에-대한-내용인가요-3"><i class="fa fa-check"></i><b>2.4.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="2.4.2" data-path="data_preparation.html"><a href="data_preparation.html#이상치에-대한-직관"><i class="fa fa-check"></i><b>2.4.2</b> 이상치에 대한 직관</a></li>
<li class="chapter" data-level="2.4.3" data-path="data_preparation.html"><a href="data_preparation.html#덥고-추운-날씨의-경계는-어디일까요"><i class="fa fa-check"></i><b>2.4.3</b> 덥고 추운 날씨의 경계는 어디일까요?</a></li>
<li class="chapter" data-level="2.4.4" data-path="data_preparation.html"><a href="data_preparation.html#이상치의-영향"><i class="fa fa-check"></i><b>2.4.4</b> 이상치의 영향</a></li>
<li class="chapter" data-level="2.4.5" data-path="data_preparation.html"><a href="data_preparation.html#how_to_deal_with_outliers_in_r"><i class="fa fa-check"></i><b>2.4.5</b> R에서 이상치를 처리하는 방법</a></li>
<li class="chapter" data-level="2.4.6" data-path="data_preparation.html"><a href="data_preparation.html#단계-이상치를-감지하는-방법"><i class="fa fa-check"></i><b>2.4.6</b> 1단계: 이상치를 감지하는 방법 🔎</a></li>
<li class="chapter" data-level="2.4.7" data-path="data_preparation.html"><a href="data_preparation.html#단계-이상치를-어떻게-할까요"><i class="fa fa-check"></i><b>2.4.7</b> 2단계: 이상치를 어떻게 할까요? 🛠️</a></li>
<li class="chapter" data-level="2.4.8" data-path="data_preparation.html"><a href="data_preparation.html#최종-생각-3"><i class="fa fa-check"></i><b>2.4.8</b> 최종 생각</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data_preparation.html"><a href="data_preparation.html#missing_data"><i class="fa fa-check"></i><b>2.5</b> 결측 데이터: 분석, 처리 및 대치</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="data_preparation.html"><a href="data_preparation.html#무엇에-대한-내용인가요-4"><i class="fa fa-check"></i><b>2.5.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="2.5.2" data-path="data_preparation.html"><a href="data_preparation.html#빈-값이-정보를-나타낼-때"><i class="fa fa-check"></i><b>2.5.2</b> 빈 값이 정보를 나타낼 때</a></li>
<li class="chapter" data-level="2.5.3" data-path="data_preparation.html"><a href="data_preparation.html#빈-값이-진짜-빈-값일-때"><i class="fa fa-check"></i><b>2.5.3</b> 빈 값이 진짜 빈 값일 때</a></li>
<li class="chapter" data-level="2.5.4" data-path="data_preparation.html"><a href="data_preparation.html#전체-행-제외하기"><i class="fa fa-check"></i><b>2.5.4</b> 전체 행 제외하기</a></li>
<li class="chapter" data-level="2.5.5" data-path="data_preparation.html"><a href="data_preparation.html#열-제외하기"><i class="fa fa-check"></i><b>2.5.5</b> 열 제외하기</a></li>
<li class="chapter" data-level="2.5.6" data-path="data_preparation.html"><a href="data_preparation.html#범주형-변수의-빈-값-처리하기"><i class="fa fa-check"></i><b>2.5.6</b> 범주형 변수의 빈 값 처리하기</a></li>
<li class="chapter" data-level="2.5.7" data-path="data_preparation.html"><a href="data_preparation.html#결측값에-어떤-패턴이-있나요"><i class="fa fa-check"></i><b>2.5.7</b> 결측값에 어떤 패턴이 있나요?</a></li>
<li class="chapter" data-level="2.5.8" data-path="data_preparation.html"><a href="data_preparation.html#수치형-변수의-결측값-처리하기"><i class="fa fa-check"></i><b>2.5.8</b> 수치형 변수의 결측값 처리하기</a></li>
<li class="chapter" data-level="2.5.9" data-path="data_preparation.html"><a href="data_preparation.html#고급-대치-방법-advanced-imputation-methods"><i class="fa fa-check"></i><b>2.5.9</b> 고급 대치 방법 (Advanced imputation methods)</a></li>
<li class="chapter" data-level="2.5.10" data-path="data_preparation.html"><a href="data_preparation.html#결론-1"><i class="fa fa-check"></i><b>2.5.10</b> 결론</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data_preparation.html"><a href="data_preparation.html#considerations-involving-time"><i class="fa fa-check"></i><b>2.6</b> 시간과 관련된 고려 사항</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="data_preparation.html"><a href="data_preparation.html#무엇에-대한-내용인가요-5"><i class="fa fa-check"></i><b>2.6.1</b> 무엇에 대한 내용인가요?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html"><i class="fa fa-check"></i><b>3</b> 최적 변수 선택</a>
<ul>
<li class="chapter" data-level="3.1" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#general_aspects_selecting_best_variables"><i class="fa fa-check"></i><b>3.1</b> 최적 변수 선택의 일반적 측면</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#무엇에-대한-내용인가요-6"><i class="fa fa-check"></i><b>3.1.1</b> 무엇에 대한 내용인가요?</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#직관"><i class="fa fa-check"></i><b>3.2</b> 직관</a></li>
<li class="chapter" data-level="3.3" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#최적의-선택"><i class="fa fa-check"></i><b>3.3</b> “최적”의 선택?</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#변수-순위-더-깊이-알아보기"><i class="fa fa-check"></i><b>3.3.1</b> 변수 순위 더 깊이 알아보기</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#선택의-특성"><i class="fa fa-check"></i><b>3.4</b> 선택의 특성</a></li>
<li class="chapter" data-level="3.5" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#변수-개선하기"><i class="fa fa-check"></i><b>3.5</b> 변수 개선하기</a></li>
<li class="chapter" data-level="3.6" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#도메인-지식에-의한-정제"><i class="fa fa-check"></i><b>3.6</b> 도메인 지식에 의한 정제</a></li>
<li class="chapter" data-level="3.7" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#변수는-그룹으로-작용합니다"><i class="fa fa-check"></i><b>3.7</b> 변수는 그룹으로 작용합니다</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#r-사례-그룹으로-작용하는-변수"><i class="fa fa-check"></i><b>3.7.1</b> R 사례: 그룹으로 작용하는 변수</a></li>
<li class="chapter" data-level="3.7.2" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#작은-사례-정보-이론-기반"><i class="fa fa-check"></i><b>3.7.2</b> 작은 사례 (정보 이론 기반)</a></li>
<li class="chapter" data-level="3.7.3" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#결론-2"><i class="fa fa-check"></i><b>3.7.3</b> 결론</a></li>
<li class="chapter" data-level="3.7.4" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#select_features_var_rank_info"><i class="fa fa-check"></i><b>3.7.4</b> 정보 이론을 사용한 최적 특성 순위 매기기</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#입력-변수-간의-상관관계"><i class="fa fa-check"></i><b>3.8</b> 입력 변수 간의 상관관계</a></li>
<li class="chapter" data-level="3.9" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#단순하게-유지하기"><i class="fa fa-check"></i><b>3.9</b> 단순하게 유지하기</a></li>
<li class="chapter" data-level="3.10" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#클러스터링에서의-변수-선택"><i class="fa fa-check"></i><b>3.10</b> 클러스터링에서의 변수 선택?</a></li>
<li class="chapter" data-level="3.11" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#실무에서-최적-변수-선택하기"><i class="fa fa-check"></i><b>3.11</b> 실무에서 최적 변수 선택하기</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#짧은-답변"><i class="fa fa-check"></i><b>3.11.1</b> 짧은 답변</a></li>
<li class="chapter" data-level="3.11.2" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#긴-답변"><i class="fa fa-check"></i><b>3.11.2</b> 긴 답변</a></li>
<li class="chapter" data-level="3.11.3" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#자신만의-지식-창출하기"><i class="fa fa-check"></i><b>3.11.3</b> 자신만의 지식 창출하기</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#타겟-프로파일링"><i class="fa fa-check"></i><b>3.12</b> 타겟 프로파일링</a>
<ul>
<li class="chapter" data-level="3.12.1" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#profiling_target_cross_plot"><i class="fa fa-check"></i><b>3.12.1</b> <code>cross_plot</code> 사용하기 (dataViz)</a></li>
<li class="chapter" data-level="3.12.2" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#target-profiling-using-boxplots"><i class="fa fa-check"></i><b>3.12.2</b> 박스 플롯 사용하기</a></li>
<li class="chapter" data-level="3.12.3" data-path="selecting_best_variables.html"><a href="selecting_best_variables.html#target-profiling-using-density-histograms"><i class="fa fa-check"></i><b>3.12.3</b> 밀도 히스토그램 사용하기</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="model-performance.html"><a href="model-performance.html"><i class="fa fa-check"></i><b>4</b> 모델 성능 평가</a>
<ul>
<li class="chapter" data-level="4.1" data-path="model-performance.html"><a href="model-performance.html#knowing_the_error"><i class="fa fa-check"></i><b>4.1</b> 오차 알기</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="model-performance.html"><a href="model-performance.html#무엇에-대한-내용인가요-10"><i class="fa fa-check"></i><b>4.1.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="4.1.2" data-path="model-performance.html"><a href="model-performance.html#예상치-못한-동작-줄이기"><i class="fa fa-check"></i><b>4.1.2</b> 예상치 못한 동작 줄이기</a></li>
<li class="chapter" data-level="4.1.3" data-path="model-performance.html"><a href="model-performance.html#교차-검증cross-validation-cv으로-설명해-보겠습니다"><i class="fa fa-check"></i><b>4.1.3</b> 교차 검증(Cross-Validation, CV)으로 설명해 보겠습니다</a></li>
<li class="chapter" data-level="4.1.4" data-path="model-performance.html"><a href="model-performance.html#그렇다면-오차란-무엇인가요"><i class="fa fa-check"></i><b>4.1.4</b> 그렇다면 오차란 무엇인가요?</a></li>
<li class="chapter" data-level="4.1.5" data-path="model-performance.html"><a href="model-performance.html#실무에-대한-제언이-있나요"><i class="fa fa-check"></i><b>4.1.5</b> 실무에 대한 제언이 있나요?</a></li>
<li class="chapter" data-level="4.1.6" data-path="model-performance.html"><a href="model-performance.html#잊지-마세요-데이터-준비"><i class="fa fa-check"></i><b>4.1.6</b> 잊지 마세요: 데이터 준비</a></li>
<li class="chapter" data-level="4.1.7" data-path="model-performance.html"><a href="model-performance.html#마지막-생각"><i class="fa fa-check"></i><b>4.1.7</b> 마지막 생각</a></li>
<li class="chapter" data-level="4.1.8" data-path="model-performance.html"><a href="model-performance.html#더-읽어보기"><i class="fa fa-check"></i><b>4.1.8</b> 더 읽어보기</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="model-performance.html"><a href="model-performance.html#out-of-time_validation"><i class="fa fa-check"></i><b>4.2</b> 시간 외 검증 (Out-of-Time Validation)</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="model-performance.html"><a href="model-performance.html#무엇에-대한-내용인가요-11"><i class="fa fa-check"></i><b>4.2.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="4.2.2" data-path="model-performance.html"><a href="model-performance.html#어떤-종류의-데이터인가요-1"><i class="fa fa-check"></i><b>4.2.2</b> 어떤 종류의 데이터인가요?</a></li>
<li class="chapter" data-level="4.2.3" data-path="model-performance.html"><a href="model-performance.html#시간-외-검증-예시"><i class="fa fa-check"></i><b>4.2.3</b> 시간 외 검증 예시</a></li>
<li class="chapter" data-level="4.2.4" data-path="model-performance.html"><a href="model-performance.html#이득-및-리프트-분석gain-and-lift-analysis-사용하기"><i class="fa fa-check"></i><b>4.2.4</b> 이득 및 리프트 분석(Gain and Lift Analysis) 사용하기</a></li>
<li class="chapter" data-level="4.2.5" data-path="model-performance.html"><a href="model-performance.html#수치형-타겟-변수는-어떤가요"><i class="fa fa-check"></i><b>4.2.5</b> 수치형 타겟 변수는 어떤가요?</a></li>
<li class="chapter" data-level="4.2.6" data-path="model-performance.html"><a href="model-performance.html#마지막-생각-1"><i class="fa fa-check"></i><b>4.2.6</b> 마지막 생각</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="model-performance.html"><a href="model-performance.html#gain_and_lift"><i class="fa fa-check"></i><b>4.3</b> 이득 및 리프트 분석 (Gain and Lift Analysis)</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="model-performance.html"><a href="model-performance.html#무엇에-대한-내용인가요-12"><i class="fa fa-check"></i><b>4.3.1</b> 무엇에 대한 내용인가요?</a></li>
<li class="chapter" data-level="4.3.2" data-path="model-performance.html"><a href="model-performance.html#어떻게-해석하나요"><i class="fa fa-check"></i><b>4.3.2</b> 어떻게 해석하나요?</a></li>
<li class="chapter" data-level="4.3.3" data-path="model-performance.html"><a href="model-performance.html#모델을-사용하지-않는다면-어떨까요"><i class="fa fa-check"></i><b>4.3.3</b> 모델을 사용하지 않는다면 어떨까요?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="model-performance.html"><a href="model-performance.html#scoring_data"><i class="fa fa-check"></i><b>4.4</b> 데이터 스코어링 (Scoring Data)</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="model-performance.html"><a href="model-performance.html#숨겨진-직관"><i class="fa fa-check"></i><b>4.4.1</b> 숨겨진 직관</a></li>
<li class="chapter" data-level="4.4.2" data-path="model-performance.html"><a href="model-performance.html#예제를-살펴봅시다"><i class="fa fa-check"></i><b>4.4.2</b> 예제를 살펴봅시다</a></li>
<li class="chapter" data-level="4.4.3" data-path="model-performance.html"><a href="model-performance.html#모든-것은-절단점cut-point에-달려-있습니다"><i class="fa fa-check"></i><b>4.4.3</b> 모든 것은 절단점(cut point)에 달려 있습니다 📏</a></li>
<li class="chapter" data-level="4.4.4" data-path="model-performance.html"><a href="model-performance.html#최선과-최악의-시나리오"><i class="fa fa-check"></i><b>4.4.4</b> 최선과 최악의 시나리오</a></li>
<li class="chapter" data-level="4.4.5" data-path="model-performance.html"><a href="model-performance.html#분류기-비교"><i class="fa fa-check"></i><b>4.4.5</b> 분류기 비교</a></li>
<li class="chapter" data-level="4.4.6" data-path="model-performance.html"><a href="model-performance.html#r로-직접-해보기"><i class="fa fa-check"></i><b>4.4.6</b> R로 직접 해보기!</a></li>
<li class="chapter" data-level="4.4.7" data-path="model-performance.html"><a href="model-performance.html#결론-4"><i class="fa fa-check"></i><b>4.4.7</b> 결론</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>5</b> 부록 (APPENDIX)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="appendix.html"><a href="appendix.html#appendix-percentiles"><i class="fa fa-check"></i><b>5.1</b> 백분위수의 마법</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="appendix.html"><a href="appendix.html#백분위수를-계산하는-방법"><i class="fa fa-check"></i><b>5.1.1</b> 백분위수를 계산하는 방법</a></li>
<li class="chapter" data-level="5.1.2" data-path="appendix.html"><a href="appendix.html#사용자-정의-분위수-계산"><i class="fa fa-check"></i><b>5.1.2</b> 사용자 정의 분위수 계산</a></li>
<li class="chapter" data-level="5.1.3" data-path="appendix.html"><a href="appendix.html#대부분의-값이-어디에-있는지-표시하기"><i class="fa fa-check"></i><b>5.1.3</b> 대부분의 값이 어디에 있는지 표시하기</a></li>
<li class="chapter" data-level="5.1.4" data-path="appendix.html"><a href="appendix.html#백분위수-시각화"><i class="fa fa-check"></i><b>5.1.4</b> 백분위수 시각화</a></li>
<li class="chapter" data-level="5.1.5" data-path="appendix.html"><a href="appendix.html#순위-및-상위하위-x-개념"><i class="fa fa-check"></i><b>5.1.5</b> 순위 및 상위/하위 ‘X%’ 개념</a></li>
<li class="chapter" data-level="5.1.6" data-path="appendix.html"><a href="appendix.html#데이터-스코어링에서의-백분위수"><i class="fa fa-check"></i><b>5.1.6</b> 데이터 스코어링에서의 백분위수</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="appendix.html"><a href="appendix.html#funmodeling-quick-start"><i class="fa fa-check"></i><b>5.2</b> <code>funModeling</code> 퀵스타트</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="appendix.html"><a href="appendix.html#블랙박스-열어보기"><i class="fa fa-check"></i><b>5.2.1</b> 블랙박스 열어보기</a></li>
<li class="chapter" data-level="5.2.2" data-path="appendix.html"><a href="appendix.html#탐색적-데이터-분석-eda"><i class="fa fa-check"></i><b>5.2.2</b> 탐색적 데이터 분석 (EDA)</a></li>
<li class="chapter" data-level="5.2.3" data-path="appendix.html"><a href="appendix.html#상관관계"><i class="fa fa-check"></i><b>5.2.3</b> 상관관계</a></li>
<li class="chapter" data-level="5.2.4" data-path="appendix.html"><a href="appendix.html#데이터-준비"><i class="fa fa-check"></i><b>5.2.4</b> 데이터 준비</a></li>
<li class="chapter" data-level="5.2.5" data-path="appendix.html"><a href="appendix.html#이상치outliers-데이터-준비"><i class="fa fa-check"></i><b>5.2.5</b> 이상치(Outliers) 데이터 준비</a></li>
<li class="chapter" data-level="5.2.6" data-path="appendix.html"><a href="appendix.html#예측-모델-성능"><i class="fa fa-check"></i><b>5.2.6</b> 예측 모델 성능</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="download-book.html"><a href="download-book.html"><i class="fa fa-check"></i><b>6</b> 도서 다운로드</a></li>
<li class="chapter" data-level="" data-path="참고-문헌-references.html"><a href="참고-문헌-references.html"><i class="fa fa-check"></i>참고 문헌 (References)</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">데이터 과학 라이브 북 (Data Science Live Book)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendix" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> 부록 (APPENDIX)<a href="appendix.html#appendix" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>보충 자료입니다.</p>
<div id="appendix-percentiles" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> 백분위수의 마법<a href="appendix.html#appendix-percentiles" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>백분위수는 데이터 분석에서 매우 중요한 개념이므로 이 책에서 광범위하게 다룰 것입니다. 백분위수는 다른 관측치와 비교하여 각 관측치를 고려합니다. 고립된 숫자는 의미가 없을 수 있지만, 다른 숫자와 비교할 때 분포의 개념이 나타납니다.</p>
<p>백분위수는 프로파일링뿐만 아니라 예측 모델의 성능을 평가하는 데에도 사용됩니다.</p>
<p><br></p>
<div class="figure"><span style="display:block;" id="fig:how-to-calculate-percentiles"></span>
<img src="exploratory_data_analysis/how_to_calculate_percentiles.png" alt="백분위수 계산 방법" width="100%"  />
<p class="caption">
Figure 5.1: 백분위수 계산 방법
</p>
</div>
<p><br></p>
<p><strong>데이터셋, 계속하기 전의 제언:</strong></p>
<p>이 데이터셋은 세계 개발과 관련된 많은 지표를 포함하고 있습니다. 프로파일링 예제와 상관없이, 사회학자, 연구자 등 이러한 종류의 데이터 분석에 관심이 있는 사람들에게 바로 사용할 수 있는 표를 제공하는 것이 목적입니다.</p>
<p>원본 데이터 소스는 <a href="http://databank.worldbank.org/data/reports.aspx?source=2&Topic=11#" target="blank">http://databank.worldbank.org</a>입니다. 거기에서 모든 변수를 설명하는 데이터 사전을 찾을 수 있습니다.</p>
<p>이 섹션에서는 이미 분석을 위해 준비된 표를 사용할 것입니다. 단계별 데이터 준비 과정 전체는 <a href="exploratory_data_analysis.html#profiling">프로파일링</a> 장에 있습니다.</p>
<p>지표의 의미는 data.worldbank.org에서 확인할 수 있습니다. 예를 들어, <code>EN.POP.SLUM.UR.ZS</code>가 무엇을 의미하는지 알고 싶다면 <a href="http://data.worldbank.org/indicator/EN.POP.SLUM.UR.ZS를" class="uri">http://data.worldbank.org/indicator/EN.POP.SLUM.UR.ZS를</a> 입력하면 됩니다.</p>
<p><br></p>
<div id="백분위수를-계산하는-방법" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> 백분위수를 계산하는 방법<a href="appendix.html#백분위수를-계산하는-방법" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>백분위수를 얻는 방법은 여러 가지가 있습니다. 보간법(interpolation)을 기반으로 할 때 가장 쉬운 방법은 변수를 오름차순으로 정렬하고, 원하는 백분위수(예: 75%)를 선택한 다음, <em>정렬된 모집단의 75%를 선택하고자 할 때 최대값이 무엇인지</em> 관찰하는 것입니다.</p>
<p>이제 계산 과정 배후에서 <em>무슨 일이 일어나고 있는지</em> 최대한 제어할 수 있도록 작은 샘플을 유지하는 기술을 사용할 것입니다.</p>
<p>무작위로 10개 국가를 추출하고, 사용할 변수인 <code>rural_poverty_headcount</code> 벡터를 출력합니다.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="appendix.html#cb338-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb338-2"><a href="appendix.html#cb338-2" tabindex="-1"></a></span>
<span id="cb338-3"><a href="appendix.html#cb338-3" tabindex="-1"></a>data_world_wide <span class="ot">=</span></span>
<span id="cb338-4"><a href="appendix.html#cb338-4" tabindex="-1"></a>  <span class="fu">read.delim</span>(<span class="at">file=</span><span class="st">&quot;https://goo.gl/NNYhCW&quot;</span>, </span>
<span id="cb338-5"><a href="appendix.html#cb338-5" tabindex="-1"></a>             <span class="at">header =</span> T</span>
<span id="cb338-6"><a href="appendix.html#cb338-6" tabindex="-1"></a>             )</span></code></pre></div>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="appendix.html#cb339-1" tabindex="-1"></a>data_sample <span class="ot">=</span> data_world_wide <span class="sc">%&gt;%</span></span>
<span id="cb339-2"><a href="appendix.html#cb339-2" tabindex="-1"></a>  <span class="fu">filter</span>(Country.Name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Kazakhstan&quot;</span>, <span class="st">&quot;Zambia&quot;</span>, <span class="st">&quot;Mauritania&quot;</span>, <span class="st">&quot;Malaysia&quot;</span>, <span class="st">&quot;Sao Tome and Principe&quot;</span>, <span class="st">&quot;Colombia&quot;</span>, <span class="st">&quot;Haiti&quot;</span>, <span class="st">&quot;Fiji&quot;</span>, <span class="st">&quot;Sierra Leone&quot;</span>, <span class="st">&quot;Morocco&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb339-3"><a href="appendix.html#cb339-3" tabindex="-1"></a>  <span class="fu">arrange</span>(rural_poverty_headcount)</span>
<span id="cb339-4"><a href="appendix.html#cb339-4" tabindex="-1"></a></span>
<span id="cb339-5"><a href="appendix.html#cb339-5" tabindex="-1"></a>data_sample <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country.Name, rural_poverty_headcount)</span></code></pre></div>
<pre><code>##             Country.Name rural_poverty_headcount
## 1               Malaysia                     1.6
## 2             Kazakhstan                     4.4
## 3                Morocco                    14.4
## 4               Colombia                    40.3
## 5                   Fiji                    44.0
## 6             Mauritania                    59.4
## 7  Sao Tome and Principe                    59.4
## 8           Sierra Leone                    66.1
## 9                  Haiti                    74.9
## 10                Zambia                    77.9</code></pre>
<p>벡터는 학습 목적으로만 정렬되었음을 유의하십시오. <em>프로파일링 장에서 언급했듯이, 우리의 눈은 순서를 좋아합니다.</em></p>
<p>이제 <code>rural_poverty_headcount</code> 변수(국가 빈곤선 이하로 생활하는 농촌 인구의 비율)에 <code>quantile</code> 함수를 적용합니다:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="appendix.html#cb341-1" tabindex="-1"></a><span class="fu">quantile</span>(data_sample<span class="sc">$</span>rural_poverty_headcount)</span></code></pre></div>
<pre><code>##     0%    25%    50%    75%   100% 
##  1.600 20.875 51.700 64.425 77.900</code></pre>
<p><strong>분석</strong></p>
<ul>
<li><strong>백분위수 50%</strong>: 국가의 50%(5개 국가)가 <code>rural_poverty_headcount</code> 51.7 미만입니다. 마지막 도표에서 확인할 수 있습니다. 해당 국가는 피지, 콜롬비아, 모로코, 카자흐스탄, 말레이시아입니다.</li>
<li><strong>백분위수 25%</strong>: 국가의 25%가 20.87 미만입니다. 여기서 보간법이 사용된 것을 볼 수 있는데, 25%는 약 2.5개 국가를 나타내기 때문입니다. 이 값을 사용하여 국가를 필터링하면 모로코, 카자흐스탄, 말레이시아의 세 국가를 얻게 됩니다.</li>
</ul>
<p>다양한 유형의 분위수와 그 보간법에 대한 더 많은 정보는 <code>help("quantile")</code>를 참조하십시오.</p>
<div id="의미적-설명-얻기" class="section level4 hasAnchor" number="5.1.1.1">
<h4><span class="header-section-number">5.1.1.1</span> 의미적 설명 얻기<a href="appendix.html#의미적-설명-얻기" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>앞선 예제로부터 다음과 같이 말할 수 있습니다:</p>
<ul>
<li><em>“국가의 절반은 농촌 빈곤율이 51.7%에 달합니다.”</em></li>
<li><em>“국가의 4분의 3은 농촌 빈곤율이 최대 64.4%입니다.”</em> (국가를 오름차순으로 정렬했을 때 기준).</li>
</ul>
<p><strong>그 반대로</strong> 생각할 수도 있습니다:</p>
<ul>
<li><em>“가장 높은 농촌 빈곤 수치를 보이는 국가 중 4분의 1은 그 비율이 최소 64.4%입니다.”</em></li>
</ul>
</div>
</div>
<div id="사용자-정의-분위수-계산" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> 사용자 정의 분위수 계산<a href="appendix.html#사용자-정의-분위수-계산" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>일반적으로 우리는 특정 분위수를 계산하고 싶어 합니다. 예시 변수는 <code>gini_index</code>입니다.</p>
<p><strong>지니 계수(Gini index)란 무엇인가요?</strong></p>
<p>소득이나 부의 불평등을 측정하는 지표입니다.</p>
<ul>
<li>지니 계수가 <strong>0</strong>이면 모든 값이 동일한(예: 모든 사람의 소득이 동일함) <strong>완전 평등</strong>을 의미합니다.</li>
<li>지니 계수가 <strong>1</strong>(또는 100%)이면 값 사이의 <strong>최대 불평등</strong>을 의미합니다(예: 많은 사람들 중 단 한 사람만 모든 소득이나 소비를 가지고 있고 다른 모든 사람들은 전혀 없는 경우, 지니 계수는 1에 매우 가까워집니다).</li>
</ul>
<p>출처: <a href="https://en.wikipedia.org/wiki/Gini_coefficient" class="uri">https://en.wikipedia.org/wiki/Gini_coefficient</a></p>
<p><strong>R 예제</strong>:</p>
<p>지니 계수 변수의 20, 40, 60, 80분위수를 얻으려면 다시 <code>quantile</code> 함수를 사용합니다.</p>
<p>이 사례와 같이 빈 값이 있는 경우 <code>na.rm=TRUE</code> 매개변수가 필요합니다:</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="appendix.html#cb343-1" tabindex="-1"></a><span class="co"># 여러 분위수를 한 번에 얻을 수도 있습니다.</span></span>
<span id="cb343-2"><a href="appendix.html#cb343-2" tabindex="-1"></a>p_custom <span class="ot">=</span> <span class="fu">quantile</span>(data_world_wide<span class="sc">$</span>gini_index, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.4</span>, <span class="fl">0.6</span>, <span class="fl">0.8</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb343-3"><a href="appendix.html#cb343-3" tabindex="-1"></a>p_custom</span></code></pre></div>
<pre><code>##    20%    40%    60%    80% 
## 31.624 35.244 41.076 46.148</code></pre>
</div>
<div id="대부분의-값이-어디에-있는지-표시하기" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> 대부분의 값이 어디에 있는지 표시하기<a href="appendix.html#대부분의-값이-어디에-있는지-표시하기" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>기술 통계에서 우리는 모집단을 일반적인 용어로 설명하고자 합니다. 두 개의 백분위수를 사용하여 범위에 대해 말할 수 있습니다. 모집단의 80%를 설명하기 위해 10% 및 90% 백분위수를 사용해 봅시다.</p>
<p><em>국가의 80%에서 빈곤율은 0.075%에서 54.4% 사이입니다.</em> (여기서 80%인 이유는 모집단의 가운데에 집중하여 90번째 백분위수에서 10번째 백분위수를 뺐기 때문입니다.)</p>
<p>80%를 모집단의 대다수로 간주한다면 이렇게 말할 수 있을 것입니다: <em>“일반적으로(또는 일반적인 용어로) 빈곤율은 0.07%에서 54.4%까지입니다.”</em> 이것이 의미적인 설명입니다.</p>
<p>우리는 대부분의 사례가 어디에 있는지 설명하기 위해 모집단의 80%를 살펴보았는데, 이는 좋은 숫자로 보입니다. 또한 90% 범위(95번째 백분위수 - 0.5번째 백분위수)를 사용할 수도 있었을 것입니다.</p>
<div id="백분위수percentile는-사분위수quartile와-관련이-있나요" class="section level4 hasAnchor" number="5.1.3.1">
<h4><span class="header-section-number">5.1.3.1</span> 백분위수(Percentile)는 사분위수(Quartile)와 관련이 있나요?<a href="appendix.html#백분위수percentile는-사분위수quartile와-관련이-있나요" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>사분위수(Quartile)</strong>는 25, 50, 75번째 백분위수(분기 또는 ‘Q’)를 가리키는 정식 명칭입니다. 인구의 50%를 살펴보려면 제3사분위수(또는 75번째 백분위수)에서 제1사분위수(25번째 백분위수)를 빼서 데이터의 50%가 집중된 위치를 구해야 하며, 이를 <strong>사분위수 범위(inter-quartile range)</strong> 또는 IQR이라고 합니다.</p>
<p>백분위수 vs. 분위수 vs. 사분위수</p>
<pre><code>0 사분위수 = 0 분위수 = 0 백분위수
1 사분위수 = 0.25 분위수 = 25 백분위수
2 사분위수 = .5 분위수 = 50 백분위수 (중앙값)
3 사분위수 = .75 분위수 = 75 백분위수
4 사분위수 = 1 분위수 = 100 백분위수</code></pre>
<p>출처: <span class="citation">(<a href="#ref-perc_quan_quar">stats.stackexchange.com 2017b</a>)</span>.</p>
</div>
</div>
<div id="백분위수-시각화" class="section level3 hasAnchor" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> 백분위수 시각화<a href="appendix.html#백분위수-시각화" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>각 백분위수가 위치한 곳과 함께 히스토그램을 그리면 개념을 이해하는 데 도움이 될 수 있습니다:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="appendix.html#cb346-1" tabindex="-1"></a>quantiles_var <span class="ot">=</span> </span>
<span id="cb346-2"><a href="appendix.html#cb346-2" tabindex="-1"></a>  <span class="fu">quantile</span>(data_world_wide<span class="sc">$</span>poverty_headcount_1<span class="fl">.9</span>, </span>
<span id="cb346-3"><a href="appendix.html#cb346-3" tabindex="-1"></a>           <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>), </span>
<span id="cb346-4"><a href="appendix.html#cb346-4" tabindex="-1"></a>           <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb346-5"><a href="appendix.html#cb346-5" tabindex="-1"></a>           )</span>
<span id="cb346-6"><a href="appendix.html#cb346-6" tabindex="-1"></a></span>
<span id="cb346-7"><a href="appendix.html#cb346-7" tabindex="-1"></a>df_p <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">value=</span>quantiles_var, </span>
<span id="cb346-8"><a href="appendix.html#cb346-8" tabindex="-1"></a>                <span class="at">quantile=</span><span class="fu">c</span>(<span class="st">&quot;25th&quot;</span>, <span class="st">&quot;50th&quot;</span>, <span class="st">&quot;75th&quot;</span>)</span>
<span id="cb346-9"><a href="appendix.html#cb346-9" tabindex="-1"></a>                )</span>
<span id="cb346-10"><a href="appendix.html#cb346-10" tabindex="-1"></a></span>
<span id="cb346-11"><a href="appendix.html#cb346-11" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb346-12"><a href="appendix.html#cb346-12" tabindex="-1"></a><span class="fu">ggplot</span>(data_world_wide, <span class="fu">aes</span>(poverty_headcount_1<span class="fl">.9</span>)) <span class="sc">+</span> </span>
<span id="cb346-13"><a href="appendix.html#cb346-13" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb346-14"><a href="appendix.html#cb346-14" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data=</span>df_p, </span>
<span id="cb346-15"><a href="appendix.html#cb346-15" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">xintercept=</span>value, </span>
<span id="cb346-16"><a href="appendix.html#cb346-16" tabindex="-1"></a>                 <span class="at">colour =</span> quantile),</span>
<span id="cb346-17"><a href="appendix.html#cb346-17" tabindex="-1"></a>             <span class="at">show.legend =</span> <span class="cn">TRUE</span>, </span>
<span id="cb346-18"><a href="appendix.html#cb346-18" tabindex="-1"></a>             <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span></span>
<span id="cb346-19"><a href="appendix.html#cb346-19" tabindex="-1"></a>             ) <span class="sc">+</span> </span>
<span id="cb346-20"><a href="appendix.html#cb346-20" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:profiling-numerical-variable"></span>
<img src="30_appendix_files/figure-html/profiling-numerical-variable-1.png" alt="백분위수 시각화" width="480"  />
<p class="caption">
Figure 5.2: 백분위수 시각화
</p>
</div>
<p>25번째 백분위수 이전의 모든 회색 막대를 모두 합하면, 75번째 백분위수 이후의 회색 막대 합계와 거의 비슷할 것입니다.</p>
<p>마지막 도표에서 IQR은 첫 번째와 마지막 점선 사이에 나타나며 인구의 50%를 포함하고 있습니다.</p>
</div>
<div id="순위-및-상위하위-x-개념" class="section level3 hasAnchor" number="5.1.5">
<h3><span class="header-section-number">5.1.5</span> 순위 및 상위/하위 ‘X%’ 개념<a href="appendix.html#순위-및-상위하위-x-개념" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>순위 개념은 경기에서 보는 것과 동일합니다. 이는 _pop_living_slums 변수에서 가장 높은 비율을 가진 국가는 어디인가요?_와 같은 질문에 답할 수 있게 해줍니다.</p>
<p>우리는 <code>dplyr</code> 패키지의 <code>dense_rank</code> 함수를 사용할 것입니다. 각 국가에 위치(순위)를 할당하지만, 우리는 내림차순(가장 높은 값이 1순위)으로 할당하고 싶습니다.</p>
<p>이제 살펴볼 변수는 다음과 같습니다: <em>슬럼(slums)에 거주하는 인구는 슬럼 가구에 거주하는 도시 인구의 비율입니다. 슬럼 가구는 동일한 지붕 아래 거주하며 다음 조건 중 하나 이상이 부족한 개인들의 집합으로 정의됩니다: 개선된 식수 이용, 개선된 위생 시설 이용, 충분한 주거 면적, 주택의 내구성.</em></p>
<p>답변할 질문: <em>슬럼 거주 비율이 가장 높은 상위 6개 국가는 어디인가요?</em></p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="appendix.html#cb347-1" tabindex="-1"></a><span class="co"># 순위 변수 생성</span></span>
<span id="cb347-2"><a href="appendix.html#cb347-2" tabindex="-1"></a>data_world_wide<span class="sc">$</span>rank_pop_living_slums <span class="ot">=</span> </span>
<span id="cb347-3"><a href="appendix.html#cb347-3" tabindex="-1"></a>  <span class="fu">dense_rank</span>(<span class="fu">desc</span>(data_world_wide<span class="sc">$</span>pop_living_slums))</span></code></pre></div>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="appendix.html#cb348-1" tabindex="-1"></a><span class="co"># 순위별로 데이터 정렬</span></span>
<span id="cb348-2"><a href="appendix.html#cb348-2" tabindex="-1"></a>data_world_wide <span class="ot">=</span> data_world_wide <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(rank_pop_living_slums)</span>
<span id="cb348-3"><a href="appendix.html#cb348-3" tabindex="-1"></a></span>
<span id="cb348-4"><a href="appendix.html#cb348-4" tabindex="-1"></a><span class="co"># 상위 6개 결과 출력</span></span>
<span id="cb348-5"><a href="appendix.html#cb348-5" tabindex="-1"></a>data_world_wide <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country.Name, rank_pop_living_slums) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##               Country.Name rank_pop_living_slums
## 1              South Sudan                     1
## 2 Central African Republic                     2
## 3                    Sudan                     3
## 4                     Chad                     4
## 5    Sao Tome and Principe                     5
## 6            Guinea-Bissau                     6</code></pre>
<p>또한 _에콰도르(Ecuador)는 몇 위인가요?_라고 물을 수 있습니다:</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="appendix.html#cb350-1" tabindex="-1"></a>data_world_wide <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Country.Name <span class="sc">==</span> <span class="st">&quot;Ecuador&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(rank_pop_living_slums)</span></code></pre></div>
<pre><code>##   rank_pop_living_slums
## 1                    57</code></pre>
<div id="상위-및-하위-x-개념" class="section level5 hasAnchor" number="5.1.5.0.1">
<h5><span class="header-section-number">5.1.5.0.1</span> 상위 및 하위 ‘X%’ 개념<a href="appendix.html#상위-및-하위-x-개념" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>우리가 답하고 싶어 할 만한 다른 질문들: <em>하위 10%의 가장 낮은 값을 얻을 수 있는 값은 무엇일까요?</em></p>
<p>10번째 백분위수가 정답입니다:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="appendix.html#cb352-1" tabindex="-1"></a><span class="fu">quantile</span>(data_world_wide<span class="sc">$</span>pop_living_slums, <span class="at">probs =</span> <span class="fl">0.1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  10% 
## 12.5</code></pre>
<p>반대로 생각해 봅시다: <em>상위 10%의 가장 높은 값을 얻을 수 있는 값은 무엇일까요?</em></p>
<p>90번째 백분위수가 정답입니다. 이 값보다 큰 모든 사례를 필터링할 수 있습니다:</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="appendix.html#cb354-1" tabindex="-1"></a><span class="fu">quantile</span>(data_world_wide<span class="sc">$</span>pop_living_slums, </span>
<span id="cb354-2"><a href="appendix.html#cb354-2" tabindex="-1"></a>         <span class="at">probs =</span> <span class="fl">0.9</span>, </span>
<span id="cb354-3"><a href="appendix.html#cb354-3" tabindex="-1"></a>         <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb354-4"><a href="appendix.html#cb354-4" tabindex="-1"></a>         ) </span></code></pre></div>
<pre><code>##  90% 
## 75.2</code></pre>
</div>
</div>
<div id="데이터-스코어링에서의-백분위수" class="section level3 hasAnchor" number="5.1.6">
<h3><span class="header-section-number">5.1.6</span> 데이터 스코어링에서의 백분위수<a href="appendix.html#데이터-스코어링에서의-백분위수" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>이 개념을 사용하는 두 개의 장이 있습니다:</p>
<ul>
<li><a href="#data_scoring">데이터 스코어링</a></li>
<li><a href="model-performance.html#gain_and_lift">이득 및 리프트 분석</a></li>
</ul>
<p>기본적인 아이디어는 이진 변수(<code>예</code>/<code>아니오</code>)를 예측하는 예측 모델을 개발하는 것입니다. 예를 들어 마케팅 캠페인에서 사용할 새로운 케이스의 스코어를 매겨야 한다고 가정해 봅시다. 답변해야 할 질문은 다음과 같습니다:</p>
<p><em>잠재적인 신규 매출의 50%를 포착하기 위해 영업 사원에게 제안할 스코어 값은 얼마인가요?</em> 정답은 스코어링 값에 대한 백분위수 분석과 현재 타겟의 누적 분석을 결합하여 얻을 수 있습니다.</p>
<div class="figure"><span style="display:block;" id="fig:gain-lift-curve"></span>
<img src="model_performance/gain_curve.png" alt="이득 및 리프트 곡선 (모델 성능)" width="80%"  />
<p class="caption">
Figure 5.3: 이득 및 리프트 곡선 (모델 성능)
</p>
</div>
<p><br></p>
<div id="사례-연구-부의-분포" class="section level4 hasAnchor" number="5.1.6.1">
<h4><span class="header-section-number">5.1.6.1</span> 사례 연구: 부의 분포<a href="appendix.html#사례-연구-부의-분포" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>부의 분포는 지니 계수와 유사하며 불평등에 초점을 맞춥니다. 이는 (소득과는 다른) 소유 자산을 측정하여, 사람들이 사는 곳에 따라 무엇을 획득할 수 있는지에 대해 국가 간 비교를 더 공정하게 만듭니다.
더 정확한 정의는 <em>Wikipedia</em> 기사와 _Global Wealth Report 2013_을 참조하십시오. 각각 자료 <span class="citation">(<a href="#ref-distr_wealth">Wikipedia 2017a</a>)</span>와 <span class="citation">(<a href="#ref-global_wealth">Suisse 2013</a>)</span>입니다.</p>
<p>_Wikipedia_의 인용(자료 <span class="citation">(<a href="#ref-distr_wealth">Wikipedia 2017a</a>)</span>):</p>
<blockquote>
<p>세계 부의 절반은 인구의 상위 1%가 소유하고 있습니다.</p>
</blockquote>
<blockquote>
<p>상위 10%의 성인이 85%를 보유하고 있으며, 나머지 하위 90%가 전 세계 총자산의 15%를 보유하고 있습니다.</p>
</blockquote>
<blockquote>
<p>상위 30%의 성인이 총자산의 97%를 보유하고 있습니다.</p>
</blockquote>
<p>앞에서 했던 것처럼 세 번째 문장으로부터 다음과 같이 말할 수 있습니다: <em>“전체 부의 3%가 성인 70%에게 분배되어 있습니다.”</em></p>
<p><code>상위 10%</code> 및 <code>상위 30%</code> 지표는 분위수 <code>0.1</code> 및 <code>0.3</code>에 해당합니다. 여기서 부(Wealth)는 수치 변수입니다.</p>
<p><br></p>
<hr />
<p><img src="introduction/spacer_bar.png" /><!-- --></p>
<hr />
<p><br></p>
</div>
</div>
</div>
<div id="funmodeling-quick-start" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> <code>funModeling</code> 퀵스타트<a href="appendix.html#funmodeling-quick-start" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>이 패키지에는 탐색적 데이터 분석, 데이터 준비 및 모델 성능과 관련된 일련의 함수들이 포함되어 있습니다. 비즈니스, 연구 및 교육(교수 및 학생) 분야의 사람들이 주로 사용합니다.</p>
<p><code>funModeling</code>은 이 책에서 다루는 다양한 주제를 설명하는 데 대부분의 기능이 사용된다는 점에서 이 책과 밀접한 관련이 있습니다.</p>
<div id="블랙박스-열어보기" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> 블랙박스 열어보기<a href="appendix.html#블랙박스-열어보기" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>일부 함수에는 인라인 주석이 있어 사용자가 블랙박스를 열고 어떻게 개발되었는지 배우거나, 함수를 조정하거나 개선할 수 있습니다.</p>
<p>모든 함수는 잘 문서화되어 있으며, 많은 짧은 예제의 도움을 받아 모든 매개변수를 설명합니다. R 문서는 <code>help("함수_이름")</code>으로 접속할 수 있습니다.</p>
<p><strong>최신 버전 1.6.7의 중요한 변경 사항</strong> (이전 버전을 사용하던 경우에만 해당):</p>
<p>최신 버전인 1.6.7(2018년 1월 21일)부터 매개변수 <code>str_input</code>, <code>str_target</code> 및 <code>str_score</code>의 이름이 각각 <code>input</code>, <code>target</code> 및 <code>score</code>로 변경됩니다. 기능은 동일하게 유지됩니다. 프로덕션 환경에서 이전 매개변수 이름을 사용하고 있었다면 다음 릴리스까지는 계속 작동할 것입니다. 즉, 현재로서는 예를 들어 <code>str_input</code> 또는 <code>input</code>을 모두 사용할 수 있습니다.</p>
<p>또 다른 중요한 변경 사항은 <code>discretize_get_bins</code>였으며, 이는 이 문서의 뒷부분에서 자세히 설명합니다.</p>
<p><br></p>
<div id="이-퀵스타트에-대하여" class="section level4 hasAnchor" number="5.2.1.1">
<h4><span class="header-section-number">5.2.1.1</span> 이 퀵스타트에 대하여<a href="appendix.html#이-퀵스타트에-대하여" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>이 퀵스타트는 함수에만 초점을 맞추고 있습니다. 함수에 대한 모든 설명과 사용 방법 및 시점은 각 섹션 아래의 “<em><strong>여기서 더 읽어보기</strong></em>” 링크를 통해 이 책의 해당 내용으로 연결됩니다.</p>
<p>아래에는 카테고리별로 나뉜 대부분의 <code>funModeling</code> 함수들이 있습니다.</p>
</div>
</div>
<div id="탐색적-데이터-분석-eda" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> 탐색적 데이터 분석 (EDA)<a href="appendix.html#탐색적-데이터-분석-eda" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="df_status-데이터셋-상태-확인" class="section level4 hasAnchor" number="5.2.2.1">
<h4><span class="header-section-number">5.2.2.1</span> <code>df_status</code>: 데이터셋 상태 확인<a href="appendix.html#df_status-데이터셋-상태-확인" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>사용 사례: 주어진 데이터셋에 대해 0(zeros), 결측값(<code>NA</code>), 무한대, 데이터 유형 및 고유 값의 개수를 분석합니다.</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="appendix.html#cb356-1" tabindex="-1"></a><span class="fu">library</span>(funModeling)</span>
<span id="cb356-2"><a href="appendix.html#cb356-2" tabindex="-1"></a></span>
<span id="cb356-3"><a href="appendix.html#cb356-3" tabindex="-1"></a><span class="fu">df_status</span>(heart_disease)</span></code></pre></div>
<pre><code>##                  variable q_zeros p_zeros q_na p_na q_inf p_inf    type unique
## 1                     age       0    0.00    0 0.00     0     0 integer     41
## 2                  gender       0    0.00    0 0.00     0     0  factor      2
## 3              chest_pain       0    0.00    0 0.00     0     0  factor      4
## 4  resting_blood_pressure       0    0.00    0 0.00     0     0 integer     50
## 5       serum_cholestoral       0    0.00    0 0.00     0     0 integer    152
## 6     fasting_blood_sugar     258   85.15    0 0.00     0     0  factor      2
## 7         resting_electro     151   49.83    0 0.00     0     0  factor      3
## 8          max_heart_rate       0    0.00    0 0.00     0     0 integer     91
## 9             exer_angina     204   67.33    0 0.00     0     0 integer      2
## 10                oldpeak      99   32.67    0 0.00     0     0 numeric     40
## 11                  slope       0    0.00    0 0.00     0     0 integer      3
## 12      num_vessels_flour     176   58.09    4 1.32     0     0 integer      4
## 13                   thal       0    0.00    2 0.66     0     0  factor      3
## 14 heart_disease_severity     164   54.13    0 0.00     0     0 integer      5
## 15           exter_angina     204   67.33    0 0.00     0     0  factor      2
## 16      has_heart_disease       0    0.00    0 0.00     0     0  factor      2</code></pre>
<p>[🔎 <a href="#dataset-health-status"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="plot_num-수치-변수의-분포-시각화" class="section level4 hasAnchor" number="5.2.2.2">
<h4><span class="header-section-number">5.2.2.2</span> <code>plot_num</code>: 수치 변수의 분포 시각화<a href="appendix.html#plot_num-수치-변수의-분포-시각화" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>수치 변수만을 시각화합니다.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="appendix.html#cb358-1" tabindex="-1"></a><span class="fu">plot_num</span>(heart_disease)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="30_appendix_files/figure-html/unnamed-chunk-13-1.png" alt="plot_num: 수치 변수 시각화" width="480"  />
<p class="caption">
Figure 5.4: plot_num: 수치 변수 시각화
</p>
</div>
<p>Notes:</p>
<ul>
<li><code>bins</code>: 구간(bin)의 개수를 설정합니다(기본값은 10).</li>
<li><code>path_out</code>: 경로 디렉토리를 나타냅니다. 값이 있으면 플롯이 jpeg로 내보내집니다. 현재 디렉토리에 저장하려면 점(“.”)을 사용합니다.</li>
</ul>
<p>[🔎 <a href="#plotting-numerical-variable"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="profiling_num-수치-변수에-대한-여러-통계량-계산" class="section level4 hasAnchor" number="5.2.2.3">
<h4><span class="header-section-number">5.2.2.3</span> <code>profiling_num</code>: 수치 변수에 대한 여러 통계량 계산<a href="appendix.html#profiling_num-수치-변수에-대한-여러-통계량-계산" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>수치 변수에 대한 여러 통계량을 검색합니다.</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="appendix.html#cb359-1" tabindex="-1"></a><span class="fu">profiling_num</span>(heart_disease)</span></code></pre></div>
<pre><code>##                 variable        mean    std_dev variation_coef   p_01  p_05
## 1                    age  54.4389439  9.0386624      0.1660330  35.00  40.0
## 2 resting_blood_pressure 131.6897690 17.5997477      0.1336455 100.00 108.0
## 3      serum_cholestoral 246.6930693 51.7769175      0.2098840 149.00 175.1
## 4         max_heart_rate 149.6072607 22.8750033      0.1529004  95.02 108.1
## 5            exer_angina   0.3267327  0.4697945      1.4378558   0.00   0.0
## 6                oldpeak   1.0396040  1.1610750      1.1168436   0.00   0.0
## 7                  slope   1.6006601  0.6162261      0.3849825   1.00   1.0
## 8      num_vessels_flour   0.6722408  0.9374383      1.3944978   0.00   0.0
## 9 heart_disease_severity   0.9372937  1.2285357      1.3107265   0.00   0.0
##    p_25  p_50  p_75  p_95   p_99   skewness kurtosis  iqr        range_98
## 1  48.0  56.0  61.0  68.0  71.00 -0.2080241 2.465477 13.0        [35, 71]
## 2 120.0 130.0 140.0 160.0 180.00  0.7025346 3.845881 20.0      [100, 180]
## 3 211.0 241.0 275.0 326.9 406.74  1.1298741 7.398208 64.0   [149, 406.74]
## 4 133.5 153.0 166.0 181.9 191.96 -0.5347844 2.927602 32.5 [95.02, 191.96]
## 5   0.0   0.0   1.0   1.0   1.00  0.7388506 1.545900  1.0          [0, 1]
## 6   0.0   0.8   1.6   3.4   4.20  1.2634255 4.530193  1.6        [0, 4.2]
## 7   1.0   2.0   2.0   3.0   3.00  0.5057957 2.363050  1.0          [1, 3]
## 8   0.0   0.0   1.0   3.0   3.00  1.1833771 3.234941  1.0          [0, 3]
## 9   0.0   0.0   2.0   3.0   4.00  1.0532483 2.843788  2.0          [0, 4]
##         range_80
## 1       [42, 66]
## 2     [110, 152]
## 3 [188.8, 308.8]
## 4   [116, 176.6]
## 5         [0, 1]
## 6       [0, 2.8]
## 7         [1, 2]
## 8         [0, 2]
## 9         [0, 3]</code></pre>
<p>Note:</p>
<ul>
<li><code>plot_num</code>과 <code>profiling_num</code>은 수치가 아닌 변수를 자동으로 제외합니다.</li>
</ul>
<p>[🔎 <a href="#numerical-profiling-in-r"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="freq-범주형-변수의-빈도-분포-확인" class="section level4 hasAnchor" number="5.2.2.4">
<h4><span class="header-section-number">5.2.2.4</span> <code>freq</code>: 범주형 변수의 빈도 분포 확인<a href="appendix.html#freq-범주형-변수의-빈도-분포-확인" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="appendix.html#cb361-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb361-2"><a href="appendix.html#cb361-2" tabindex="-1"></a></span>
<span id="cb361-3"><a href="appendix.html#cb361-3" tabindex="-1"></a><span class="co"># 이 예시를 위해 두 개의 변수만 선택합니다.</span></span>
<span id="cb361-4"><a href="appendix.html#cb361-4" tabindex="-1"></a>heart_disease_2 <span class="ot">=</span> heart_disease <span class="sc">%&gt;%</span> <span class="fu">select</span>(chest_pain, thal)</span>
<span id="cb361-5"><a href="appendix.html#cb361-5" tabindex="-1"></a></span>
<span id="cb361-6"><a href="appendix.html#cb361-6" tabindex="-1"></a><span class="co"># 빈도 분포</span></span>
<span id="cb361-7"><a href="appendix.html#cb361-7" tabindex="-1"></a><span class="fu">freq</span>(heart_disease_2)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:distribution-categorical-variable-1"></span>
<img src="30_appendix_files/figure-html/distribution-categorical-variable-1.png" alt="freq: 범주형 변수 시각화" width="480"  />
<p class="caption">
Figure 5.5: freq: 범주형 변수 시각화
</p>
</div>
<pre><code>##   chest_pain frequency percentage cumulative_perc
## 1          4       144      47.52           47.52
## 2          3        86      28.38           75.90
## 3          2        50      16.50           92.40
## 4          1        23       7.59          100.00</code></pre>
<div class="figure"><span style="display:block;" id="fig:distribution-categorical-variable-2"></span>
<img src="30_appendix_files/figure-html/distribution-categorical-variable-2.png" alt="freq: 범주형 변수 시각화" width="480"  />
<p class="caption">
Figure 5.6: freq: 범주형 변수 시각화
</p>
</div>
<pre><code>##   thal frequency percentage cumulative_perc
## 1    3       166      54.79           54.79
## 2    7       117      38.61           93.40
## 3    6        18       5.94           99.34
## 4 &lt;NA&gt;         2       0.66          100.00</code></pre>
<pre><code>## [1] &quot;Variables processed: chest_pain, thal&quot;</code></pre>
<p>Notes:</p>
<ul>
<li><code>freq</code>는 <code>factor</code> 및 <code>character</code>만 처리하며, 범주형이 아닌 변수는 제외합니다.</li>
<li>분포표를 데이터 프레임으로 반환합니다.</li>
<li><code>input</code>이 비어 있으면 모든 범주형 변수에 대해 실행됩니다.</li>
<li><code>path_out</code>은 경로 디렉토리를 나타냅니다. 값이 있으면 플롯이 jpeg로 내보내집니다. 현재 디렉토리에 저장하려면 점(“.”)을 사용합니다.</li>
<li><code>na.rm</code>은 <code>NA</code> 값을 제외할지 여부를 나타냅니다(기본값은 <code>FALSE</code>).</li>
</ul>
<p>[🔎 <a href="#profiling-categorical-variables"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
</div>
<div id="상관관계" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> 상관관계<a href="appendix.html#상관관계" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="correlation_table-r-통계량-계산" class="section level4 hasAnchor" number="5.2.3.1">
<h4><span class="header-section-number">5.2.3.1</span> <code>correlation_table</code>: R 통계량 계산<a href="appendix.html#correlation_table-r-통계량-계산" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>범주형 변수는 건너뛰고 모든 수치 변수에 대한 R 지표(또는 피어슨 상관계수)를 검색합니다.</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="appendix.html#cb365-1" tabindex="-1"></a><span class="fu">correlation_table</span>(heart_disease, <span class="st">&quot;has_heart_disease&quot;</span>)</span></code></pre></div>
<pre><code>##                 Variable has_heart_disease
## 1      has_heart_disease              1.00
## 2 heart_disease_severity              0.83
## 3      num_vessels_flour              0.46
## 4                oldpeak              0.42
## 5                  slope              0.34
## 6                    age              0.23
## 7 resting_blood_pressure              0.15
## 8      serum_cholestoral              0.08
## 9         max_heart_rate             -0.42</code></pre>
<p>Notes:</p>
<ul>
<li>수치 변수만 분석됩니다. 타겟 변수는 반드시 수치형이어야 합니다.</li>
<li>타겟이 범주형인 경우 수치형으로 변환됩니다.</li>
</ul>
<p>[🔎 <a href="#linear-correlation"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="var_rank_info-정보-이론에-기반한-상관관계" class="section level4 hasAnchor" number="5.2.3.2">
<h4><span class="header-section-number">5.2.3.2</span> <code>var_rank_info</code>: 정보 이론에 기반한 상관관계<a href="appendix.html#var_rank_info-정보-이론에-기반한-상관관계" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>데이터 프레임의 모든 변수와 타겟 변수 사이의 여러 정보 이론 지표에 기반하여 상관관계를 계산합니다.</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="appendix.html#cb367-1" tabindex="-1"></a><span class="fu">var_rank_info</span>(heart_disease, <span class="st">&quot;has_heart_disease&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: `funs()` was deprecated in dplyr 0.8.0.
## ℹ Please use a list of either functions or lambdas:
## 
## # Simple named list: list(mean = mean, median = median)
## 
## # Auto named with `tibble::lst()`: tibble::lst(mean, median)
## 
## # Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>##                         var    en    mi           ig           gr
## en13 heart_disease_severity 1.846 0.995 0.9950837595 0.5390655068
## en12                   thal 2.032 0.209 0.2094550580 0.1680456709
## en8             exer_angina 1.767 0.139 0.1391389302 0.1526393841
## en14           exter_angina 1.767 0.139 0.1391389302 0.1526393841
## en2              chest_pain 2.527 0.205 0.2050188327 0.1180286190
## en11      num_vessels_flour 2.381 0.182 0.1815217813 0.1157736478
## en10                  slope 2.177 0.112 0.1124219069 0.0868799615
## en4       serum_cholestoral 7.481 0.561 0.5605556771 0.0795557228
## en1                  gender 1.842 0.057 0.0572537665 0.0632970555
## en9                 oldpeak 4.874 0.249 0.2491668741 0.0603576874
## en7          max_heart_rate 6.832 0.334 0.3336174096 0.0540697329
## en3  resting_blood_pressure 5.567 0.143 0.1425548155 0.0302394591
## en                      age 5.928 0.137 0.1371752885 0.0270548944
## en6         resting_electro 2.059 0.024 0.0241482908 0.0221938072
## en5     fasting_blood_sugar 1.601 0.000 0.0004593775 0.0007579095</code></pre>
<p>참고: 수치 및 범주형 변수를 분석합니다. 또한 <code>discretize_df</code>와 같이 이전에 사용된 수치 이산화 방법과 함께 사용됩니다.</p>
<p>[🔎 <a href="selecting_best_variables.html#select_features_var_rank_info"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="cross_plot-입력-변수와-타겟-변수-간의-분포-플롯" class="section level4 hasAnchor" number="5.2.3.3">
<h4><span class="header-section-number">5.2.3.3</span> <code>cross_plot</code>: 입력 변수와 타겟 변수 간의 분포 플롯<a href="appendix.html#cross_plot-입력-변수와-타겟-변수-간의-분포-플롯" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>입력 변수와 타겟 변수 사이의 상대적 및 절대적 분포를 검색합니다.
변수가 중요한지 여부를 설명하고 보고하는 데 유용합니다.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="appendix.html#cb370-1" tabindex="-1"></a><span class="fu">cross_plot</span>(<span class="at">data =</span> heart_disease, <span class="at">input =</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;oldpeak&quot;</span>), <span class="at">target =</span> <span class="st">&quot;has_heart_disease&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:profiling-variable-predictive-modeling-1"></span>
<img src="30_appendix_files/figure-html/profiling-variable-predictive-modeling-1.png" alt="cross_plot: 입력 vs. 타겟 변수 시각화" width="768"  />
<p class="caption">
Figure 5.7: cross_plot: 입력 vs. 타겟 변수 시각화
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:profiling-variable-predictive-modeling-2"></span>
<img src="30_appendix_files/figure-html/profiling-variable-predictive-modeling-2.png" alt="cross_plot: 입력 vs. 타겟 변수 시각화" width="768"  />
<p class="caption">
Figure 5.8: cross_plot: 입력 vs. 타겟 변수 시각화
</p>
</div>
<p>Notes:</p>
<ul>
<li><code>auto_binning</code>: 기본값은 <code>TRUE</code>이며, 수치 변수를 범주형으로 보여줍니다.</li>
<li><code>path_out</code>: 경로 디렉토리를 나타내며, 값이 있으면 플롯이 jpeg로 내보내집니다.</li>
<li><code>input</code>은 수치형 또는 범주형일 수 있으며, <code>target</code>은 반드시 이진(두 개의 클래스) 변수여야 합니다.</li>
<li><code>input</code>이 비어 있으면 모든 변수에 대해 실행됩니다.</li>
</ul>
<p>[🔎 <a href="selecting_best_variables.html#profiling_target_cross_plot"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="plotar-입력-변수와-타겟-변수-간의-박스플롯-및-밀도-히스토그램" class="section level4 hasAnchor" number="5.2.3.4">
<h4><span class="header-section-number">5.2.3.4</span> <code>plotar</code>: 입력 변수와 타겟 변수 간의 박스플롯 및 밀도 히스토그램<a href="appendix.html#plotar-입력-변수와-타겟-변수-간의-박스플롯-및-밀도-히스토그램" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>변수가 중요한지 여부를 설명하고 보고하는 데 유용합니다.</p>
<p><strong>박스플롯(Boxplot):</strong></p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="appendix.html#cb371-1" tabindex="-1"></a><span class="fu">plotar</span>(<span class="at">data =</span> heart_disease, <span class="at">input =</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;oldpeak&quot;</span>), <span class="at">target =</span> <span class="st">&quot;has_heart_disease&quot;</span>, <span class="at">plot_type =</span> <span class="st">&quot;boxplot&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
## ℹ Please use tidy evaluation idioms with `aes()`.
## ℹ See also `vignette(&quot;ggplot2-in-packages&quot;)` for more information.
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## Warning: The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
## ℹ Please use the `fun` argument instead.
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="figure"><span style="display:block;" id="fig:boxplot-analysis-1"></span>
<img src="30_appendix_files/figure-html/boxplot-analysis-1.png" alt="plotar (1): 박스플롯 시각화" width="384"  />
<p class="caption">
Figure 5.9: plotar (1): 박스플롯 시각화
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:boxplot-analysis-2"></span>
<img src="30_appendix_files/figure-html/boxplot-analysis-2.png" alt="plotar (1): 박스플롯 시각화" width="384"  />
<p class="caption">
Figure 5.10: plotar (1): 박스플롯 시각화
</p>
</div>
<p>[🔎 <a href="selecting_best_variables.html#target-profiling-using-boxplots"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
<p><strong>밀도 히스토그램(Density histograms):</strong></p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="appendix.html#cb374-1" tabindex="-1"></a><span class="fu">plotar</span>(<span class="at">data =</span> mtcars, <span class="at">input =</span> <span class="st">&quot;gear&quot;</span>, <span class="at">target =</span> <span class="st">&quot;cyl&quot;</span>, <span class="at">plot_type =</span> <span class="st">&quot;histdens&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: `summarise_()` was deprecated in dplyr 0.7.0.
## ℹ Please use `summarise()` instead.
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## Warning: `group_by_()` was deprecated in dplyr 0.7.0.
## ℹ Please use `group_by()` instead.
## ℹ See vignette(&#39;programming&#39;) for more help
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="figure"><span style="display:block;" id="fig:density-histogram"></span>
<img src="30_appendix_files/figure-html/density-histogram-1.png" alt="plotar (2): 밀도 히스토그램 시각화" width="384"  />
<p class="caption">
Figure 5.11: plotar (2): 밀도 히스토그램 시각화
</p>
</div>
<p>[🔎 <a href="selecting_best_variables.html#target-profiling-using-density-histograms"><strong>여기서 더 읽어보기</strong></a>]</p>
<p>Notes:</p>
<ul>
<li><code>path_out</code>: 경로 디렉토리를 나타내며, 값이 있으면 플롯이 jpeg로 내보내집니다.</li>
<li><code>input</code>이 비어 있으면 모든 수치 변수에 대해 실행됩니다(범주형 변수는 건너뜀).</li>
<li><code>input</code>은 수치형이어야 하고 타겟은 범주형이어야 합니다.</li>
<li><code>target</code>은 다중 클래스(이진 클래스뿐만 아니라)일 수 있습니다.</li>
</ul>
<p><br></p>
</div>
<div id="categ_analysis-이진-결과에-대한-정량적-분석" class="section level4 hasAnchor" number="5.2.3.5">
<h4><span class="header-section-number">5.2.3.5</span> <code>categ_analysis</code>: 이진 결과에 대한 정량적 분석<a href="appendix.html#categ_analysis-이진-결과에-대한-정량적-분석" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>범주형 입력 변수를 기반으로 이진 타겟의 대푯성(<code>perc_rows</code>)과 정확도(<code>perc_target</code>)를 각각의 입력 값별로 프로파일링합니다. 예를 들어 국가별 독감 감염률 등이 있습니다.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="appendix.html#cb378-1" tabindex="-1"></a>df_ca <span class="ot">=</span> <span class="fu">categ_analysis</span>(<span class="at">data =</span> data_country, <span class="at">input =</span> <span class="st">&quot;country&quot;</span>, <span class="at">target =</span> <span class="st">&quot;has_flu&quot;</span>)</span>
<span id="cb378-2"><a href="appendix.html#cb378-2" tabindex="-1"></a></span>
<span id="cb378-3"><a href="appendix.html#cb378-3" tabindex="-1"></a><span class="fu">head</span>(df_ca)</span></code></pre></div>
<pre><code>##          country mean_target sum_target perc_target q_rows perc_rows
## 1       Malaysia       1.000          1       0.012      1     0.001
## 2         Mexico       0.667          2       0.024      3     0.003
## 3       Portugal       0.200          1       0.012      5     0.005
## 4 United Kingdom       0.178          8       0.096     45     0.049
## 5        Uruguay       0.175         11       0.133     63     0.069
## 6         Israel       0.167          1       0.012      6     0.007</code></pre>
<p>Note:</p>
<ul>
<li><code>input</code> 변수는 반드시 범주형이어야 합니다.</li>
<li><code>target</code> 변수는 반드시 이진(두 개의 값)이어야 합니다.</li>
</ul>
<p>이 함수는 예측 모델링에서 변수의 카디널리티(cardinality)를 줄여야 할 때 데이터를 분석하는 데 사용됩니다.</p>
<p>[🔎 <a href="data_preparation.html#high_cardinality_predictive_modeling"><strong>여기서 더 읽어보기</strong></a>]</p>
</div>
</div>
<div id="데이터-준비" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> 데이터 준비<a href="appendix.html#데이터-준비" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="데이터-이산화-data-discretization" class="section level4 hasAnchor" number="5.2.4.1">
<h4><span class="header-section-number">5.2.4.1</span> 데이터 이산화 (Data discretization)<a href="appendix.html#데이터-이산화-data-discretization" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="discretize_get_bins-discretize_df-수치-변수를-범주형으로-변환" class="section level5 hasAnchor" number="5.2.4.1.1">
<h5><span class="header-section-number">5.2.4.1.1</span> <code>discretize_get_bins</code> + <code>discretize_df</code>: 수치 변수를 범주형으로 변환<a href="appendix.html#discretize_get_bins-discretize_df-수치-변수를-범주형으로-변환" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>두 개의 함수가 필요합니다: <code>discretize_get_bins</code>는 각 변수에 대한 임계값(bins)을 반환하고, <code>discretize_df</code>는 첫 번째 함수의 결과를 가져와 원하는 변수를 변환합니다. 구간화(binning) 기준은 동일 빈도(equal frequency)입니다.</p>
<p>데이터셋에서 두 개의 변수만 변환하는 예시입니다.</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="appendix.html#cb380-1" tabindex="-1"></a><span class="co"># 1단계: 원하는 변수인 &quot;max_heart_rate&quot;와 &quot;oldpeak&quot;에 대한 임계값 가져오기</span></span>
<span id="cb380-2"><a href="appendix.html#cb380-2" tabindex="-1"></a>d_bins <span class="ot">=</span> <span class="fu">discretize_get_bins</span>(<span class="at">data =</span> heart_disease, <span class="at">input =</span> <span class="fu">c</span>(<span class="st">&quot;max_heart_rate&quot;</span>, <span class="st">&quot;oldpeak&quot;</span>), <span class="at">n_bins =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## Variables processed: max_heart_rate, oldpeak</code></pre>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="appendix.html#cb382-1" tabindex="-1"></a><span class="co"># 2단계: 임계값을 적용하여 최종 처리된 데이터 프레임 얻기</span></span>
<span id="cb382-2"><a href="appendix.html#cb382-2" tabindex="-1"></a>heart_disease_discretized <span class="ot">=</span> </span>
<span id="cb382-3"><a href="appendix.html#cb382-3" tabindex="-1"></a>  <span class="fu">discretize_df</span>(<span class="at">data =</span> heart_disease, </span>
<span id="cb382-4"><a href="appendix.html#cb382-4" tabindex="-1"></a>                <span class="at">data_bins =</span> d_bins, </span>
<span id="cb382-5"><a href="appendix.html#cb382-5" tabindex="-1"></a>                <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span></span>
<span id="cb382-6"><a href="appendix.html#cb382-6" tabindex="-1"></a>                )</span></code></pre></div>
<pre><code>## Variables processed: max_heart_rate, oldpeak</code></pre>
<p>다음 이미지는 결과를 보여줍니다. 변수 이름은 동일하게 유지됨을 유의하십시오.</p>
<div class="figure"><span style="display:block;" id="fig:data-discretization"></span>
<img src="appendix/data_discretization_1.png" alt="자동 이산화 과정의 결과" width="80%"  />
<p class="caption">
Figure 5.12: 자동 이산화 과정의 결과
</p>
</div>
<p>Notes:</p>
<ul>
<li>이 2단계 절차는 새로운 데이터가 들어오는 운영 환경(production)에서 사용하도록 고안되었습니다.</li>
<li>각 구간의 최소값과 최대값은 각각 <code>-Inf</code>와 <code>Inf</code>가 됩니다.</li>
<li>최신 <code>funModeling</code> 릴리스(1.6.7)에서 수정된 사항으로 인해 특정 시나리오에서 출력이 변경될 수 있습니다. 버전 1.6.6을 사용하고 있었다면 결과를 확인하십시오. 이 변경 사항에 대한 자세한 정보는 <a href="https://s3.amazonaws.com/datascienceheroes.com/img/blog/changes_discretize_df.png">여기</a>를 참조하십시오.</li>
</ul>
<p>[🔎 <a href="data_preparation.html#data-discretization"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
</div>
<div id="convert_df_to_categoric-데이터-프레임의-모든-열을-범주형-변수로-변환" class="section level4 hasAnchor" number="5.2.4.2">
<h4><span class="header-section-number">5.2.4.2</span> <code>convert_df_to_categoric</code>: 데이터 프레임의 모든 열을 범주형 변수로 변환<a href="appendix.html#convert_df_to_categoric-데이터-프레임의-모든-열을-범주형-변수로-변환" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>수치 변수에 대한 구간화 또는 이산화 기준은 동일 빈도입니다. 팩터(factor) 변수는 문자형(character) 변수로 직접 변환됩니다.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="appendix.html#cb384-1" tabindex="-1"></a>iris_char <span class="ot">=</span> <span class="fu">convert_df_to_categoric</span>(<span class="at">data =</span> iris, <span class="at">n_bins =</span> <span class="dv">5</span>)</span>
<span id="cb384-2"><a href="appendix.html#cb384-2" tabindex="-1"></a></span>
<span id="cb384-3"><a href="appendix.html#cb384-3" tabindex="-1"></a><span class="co"># 첫 6개 행 확인</span></span>
<span id="cb384-4"><a href="appendix.html#cb384-4" tabindex="-1"></a><span class="fu">head</span>(iris_char)</span></code></pre></div>
</div>
<div id="equal_freq-수치-변수를-범주형으로-변환" class="section level4 hasAnchor" number="5.2.4.3">
<h4><span class="header-section-number">5.2.4.3</span> <code>equal_freq</code>: 수치 변수를 범주형으로 변환<a href="appendix.html#equal_freq-수치-변수를-범주형으로-변환" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>동일 빈도 기준을 사용하여 수치 벡터를 팩터(factor)로 변환합니다.</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="appendix.html#cb385-1" tabindex="-1"></a>new_age <span class="ot">=</span> <span class="fu">equal_freq</span>(heart_disease<span class="sc">$</span>age, <span class="at">n_bins =</span> <span class="dv">5</span>)</span>
<span id="cb385-2"><a href="appendix.html#cb385-2" tabindex="-1"></a></span>
<span id="cb385-3"><a href="appendix.html#cb385-3" tabindex="-1"></a><span class="co"># 결과 확인</span></span>
<span id="cb385-4"><a href="appendix.html#cb385-4" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(new_age)</span></code></pre></div>
<pre><code>## new_age 
##        n  missing distinct 
##      303        0        5 
##                                                   
## Value      [29,46) [46,54) [54,59) [59,63) [63,77]
## Frequency       63      64      71      45      60
## Proportion   0.208   0.211   0.234   0.149   0.198</code></pre>
<p>[🔎 <a href="data_preparation.html#equal-frequency-binning"><strong>여기서 더 읽어보기</strong></a>]</p>
<p>Notes:</p>
<ul>
<li><code>discretize_get_bins</code>와 달리, 이 함수는 <code>-Inf</code>와 <code>Inf</code>를 각각 최소값과 최대값으로 삽입하지 않습니다.</li>
</ul>
<p><br></p>
</div>
<div id="range01-변수를-0에서-1-사이의-범위로-스케일링" class="section level4 hasAnchor" number="5.2.4.4">
<h4><span class="header-section-number">5.2.4.4</span> <code>range01</code>: 변수를 0에서 1 사이의 범위로 스케일링<a href="appendix.html#range01-변수를-0에서-1-사이의-범위로-스케일링" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>수치 벡터를 최소값이 0이고 최대값이 1인 0에서 1 사이의 척도로 변환합니다.</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="appendix.html#cb387-1" tabindex="-1"></a>age_scaled <span class="ot">=</span> <span class="fu">range01</span>(heart_disease<span class="sc">$</span>oldpeak)</span>
<span id="cb387-2"><a href="appendix.html#cb387-2" tabindex="-1"></a></span>
<span id="cb387-3"><a href="appendix.html#cb387-3" tabindex="-1"></a><span class="co"># 결과 확인</span></span>
<span id="cb387-4"><a href="appendix.html#cb387-4" tabindex="-1"></a><span class="fu">summary</span>(age_scaled)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  0.1290  0.1677  0.2581  1.0000</code></pre>
<p><br></p>
</div>
</div>
<div id="이상치outliers-데이터-준비" class="section level3 hasAnchor" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> 이상치(Outliers) 데이터 준비<a href="appendix.html#이상치outliers-데이터-준비" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="hampel_outlier-및-tukey_outlier-이상치-임계값-계산" class="section level4 hasAnchor" number="5.2.5.1">
<h4><span class="header-section-number">5.2.5.1</span> <code>hampel_outlier</code> 및 <code>tukey_outlier</code>: 이상치 임계값 계산<a href="appendix.html#hampel_outlier-및-tukey_outlier-이상치-임계값-계산" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>두 함수 모두 이상치로 간주되는 값의 임계값을 나타내는 두 값으로 된 벡터를 검색합니다.
<code>tukey_outlier</code>와 <code>hampel_outlier</code> 함수는 <code>prep_outliers</code> 내부에서 사용됩니다.</p>
<p><strong>터키(Tukey) 방식 사용:</strong></p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="appendix.html#cb389-1" tabindex="-1"></a><span class="fu">tukey_outlier</span>(heart_disease<span class="sc">$</span>resting_blood_pressure)</span></code></pre></div>
<pre><code>## bottom_threshold    top_threshold 
##               60              200</code></pre>
<p>[🔎 <a href="data_preparation.html#detecting-outliers-using-tukey-method"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
<p><strong>햄펠(Hampel) 방식 사용:</strong></p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="appendix.html#cb391-1" tabindex="-1"></a><span class="fu">hampel_outlier</span>(heart_disease<span class="sc">$</span>resting_blood_pressure)</span></code></pre></div>
<pre><code>## bottom_threshold    top_threshold 
##           85.522          174.478</code></pre>
<p>[🔎 <a href="data_preparation.html#detecting-outliers-using-hampel-method"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
<div id="prep_outliers-데이터-프레임의-이상치-준비" class="section level4 hasAnchor" number="5.2.5.2">
<h4><span class="header-section-number">5.2.5.2</span> <code>prep_outliers</code>: 데이터 프레임의 이상치 준비<a href="appendix.html#prep_outliers-데이터-프레임의-이상치-준비" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>데이터 프레임을 가져와 <code>input</code> 매개변수에 지정된 변수들에 대해 변환된 데이터 프레임을 반환합니다. 단일 벡터로도 작동합니다.</p>
<p>두 개의 변수를 입력으로 사용하는 예시입니다:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="appendix.html#cb393-1" tabindex="-1"></a><span class="co"># Hampel 방식에 따른 임계값 가져오기</span></span>
<span id="cb393-2"><a href="appendix.html#cb393-2" tabindex="-1"></a><span class="fu">hampel_outlier</span>(heart_disease<span class="sc">$</span>max_heart_rate)</span></code></pre></div>
<pre><code>## bottom_threshold    top_threshold 
##           86.283          219.717</code></pre>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="appendix.html#cb395-1" tabindex="-1"></a><span class="co"># 임계값에서 이상치를 멈추게(stop) 하는 함수 적용</span></span>
<span id="cb395-2"><a href="appendix.html#cb395-2" tabindex="-1"></a>data_prep <span class="ot">=</span> <span class="fu">prep_outliers</span>(<span class="at">data =</span> heart_disease, <span class="at">input =</span> <span class="fu">c</span>(<span class="st">&#39;max_heart_rate&#39;</span>, <span class="st">&#39;resting_blood_pressure&#39;</span>), <span class="at">method =</span> <span class="st">&quot;hampel&quot;</span>, <span class="at">type =</span> <span class="st">&#39;stop&#39;</span>)</span></code></pre></div>
<p><code>max_heart_rate</code> 변수의 변환 전후를 확인합니다:</p>
<pre><code>## [1] &quot;변환 전 -&gt; 최소값: 71; 최대값: 202&quot;</code></pre>
<pre><code>## [1] &quot;변환 후 -&gt; 최소값: 71; 최대값: 202&quot;</code></pre>
<p>최소값은 71에서 86.23으로 변경되었으며, 최대값은 202로 동일하게 유지되었습니다.</p>
<p>참고:</p>
<ul>
<li><code>method</code>는 <code>bottom_top</code>, <code>tukey</code> 또는 <code>hampel</code>이 될 수 있습니다.</li>
<li><code>type</code>은 <code>stop</code> 또는 <code>set_na</code>가 될 수 있습니다. <code>stop</code> 인 경우 이상치로 플래그가 지정된 모든 값이 임계값으로 설정됩니다. <code>set_na</code> 인 경우 플래그가 지정된 값은 <code>NA</code>로 설정됩니다.</li>
</ul>
<p>[🔎 <a href="data_preparation.html#how_to_deal_with_outliers_in_r"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
</div>
</div>
<div id="예측-모델-성능" class="section level3 hasAnchor" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> 예측 모델 성능<a href="appendix.html#예측-모델-성능" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="gain_lift-이득-및-리프트-성능-곡선" class="section level4 hasAnchor" number="5.2.6.1">
<h4><span class="header-section-number">5.2.6.1</span> <code>gain_lift</code>: 이득 및 리프트 성능 곡선<a href="appendix.html#gain_lift-이득-및-리프트-성능-곡선" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>예측하고자 하는 클래스에 대한 스코어나 확률을 계산한 후, 이를 <code>gain_lift</code> 함수에 전달하면 성능 지표가 포함된 데이터 프레임을 반환합니다.</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="appendix.html#cb398-1" tabindex="-1"></a><span class="co"># 머신러닝 모델 생성 및 양성 케이스에 대한 스코어 가져오기</span></span>
<span id="cb398-2"><a href="appendix.html#cb398-2" tabindex="-1"></a>fit_glm <span class="ot">=</span> <span class="fu">glm</span>(has_heart_disease <span class="sc">~</span> age <span class="sc">+</span> oldpeak, <span class="at">data =</span> heart_disease, <span class="at">family =</span> binomial)</span>
<span id="cb398-3"><a href="appendix.html#cb398-3" tabindex="-1"></a>heart_disease<span class="sc">$</span>score <span class="ot">=</span> <span class="fu">predict</span>(fit_glm, <span class="at">newdata =</span> heart_disease, <span class="at">type =</span> <span class="st">&#39;response&#39;</span>)</span>
<span id="cb398-4"><a href="appendix.html#cb398-4" tabindex="-1"></a></span>
<span id="cb398-5"><a href="appendix.html#cb398-5" tabindex="-1"></a><span class="co"># 성능 지표 계산</span></span>
<span id="cb398-6"><a href="appendix.html#cb398-6" tabindex="-1"></a><span class="fu">gain_lift</span>(<span class="at">data =</span> heart_disease, <span class="at">score =</span> <span class="st">&#39;score&#39;</span>, <span class="at">target =</span> <span class="st">&#39;has_heart_disease&#39;</span>)</span></code></pre></div>
<pre><code>## Warning: The `guide` argument in `scale_*()` cannot be `FALSE`. This was deprecated in
## ggplot2 3.3.4.
## ℹ Please use &quot;none&quot; instead.
## ℹ The deprecated feature was likely used in the funModeling package.
##   Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.
## This warning is displayed once per session.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="figure"><span style="display:block;" id="fig:predictive-model-performance"></span>
<img src="30_appendix_files/figure-html/predictive-model-performance-1.png" alt="gain_lift: 예측 모델 성능 시각화" width="672"  />
<p class="caption">
Figure 5.13: gain_lift: 예측 모델 성능 시각화
</p>
</div>
<pre><code>##    Population   Gain Lift Score.Point
## 1          10  20.86 2.09   0.8185793
## 2          20  35.97 1.80   0.6967124
## 3          30  48.92 1.63   0.5657817
## 4          40  61.15 1.53   0.4901940
## 5          50  69.06 1.38   0.4033640
## 6          60  78.42 1.31   0.3344170
## 7          70  87.77 1.25   0.2939878
## 8          80  92.09 1.15   0.2473671
## 9          90  96.40 1.07   0.1980453
## 10        100 100.00 1.00   0.1195511</code></pre>
<p>[🔎 <a href="model-performance.html#gain_and_lift"><strong>여기서 더 읽어보기</strong></a>]</p>
<p><br></p>
<hr />
<p><img src="introduction/spacer_bar.png" /><!-- --></p>
<hr />

</div>
</div>
</div>
</div>
<h3>참고 문헌 (References)<a href="참고-문헌-references.html#참고-문헌-references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-perc_quan_quar" class="csl-entry">
———. 2017b. <span>“Percentile Vs Quantile Vs Quartile.”</span> <a href="https://stats.stackexchange.com/questions/156778/percentile-vs-quantile-vs-quartile">https://stats.stackexchange.com/questions/156778/percentile-vs-quantile-vs-quartile</a>.
</div>
<div id="ref-global_wealth" class="csl-entry">
Suisse, Credit. 2013. <span>“Global Wealth Report 2013.”</span> <a href="https://publications.credit-suisse.com/tasks/render/file/?fileID=BCDB1364-A105-0560-1332EC9100FF5C83">https://publications.credit-suisse.com/tasks/render/file/?fileID=BCDB1364-A105-0560-1332EC9100FF5C83</a>.
</div>
<div id="ref-distr_wealth" class="csl-entry">
Wikipedia. 2017a. <span>“Distribution of Wealth.”</span> <a href="https://en.wikipedia.org/wiki/Distribution_of_wealth">https://en.wikipedia.org/wiki/Distribution_of_wealth</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="model-performance.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="download-book.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/pablo14/data-science-live-book/edit/master/30_appendix.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  }
});
});
</script>

</body>

</html>
